// `kavach checklist` — turn review criteria into something developers read
// *before* opening a PR.
//
// This is the one command that deliberately writes into the repository: the
// point is a committed file the whole team sees, and that a coding agent picks
// up from CLAUDE.md. Nothing else Kavach does touches the project tree.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfig, loadKnowledge } from '../store/config.ts';
import { banner, c } from '../brand.ts';
import { KAVACH_VERSION, REVIEWERS, type KavachConfig, type ReviewerName } from '../types.ts';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

export interface ChecklistOptions {
  root: string;
  /** Where to write, relative to the project root. */
  out?: string;
  /** Overwrite a file Kavach did not generate. */
  force: boolean;
  /** Print to stdout instead of writing. */
  print: boolean;
}

const DEFAULT_OUT = 'REVIEW-CHECKLIST.md';
const MARKER = '<!-- generated by kavach -->';

export async function checklist(opts: ChecklistOptions): Promise<void> {
  const { config } = loadConfig(opts.root);
  const knowledge = loadKnowledge(opts.root);
  const reviewers = relevantReviewers(config);
  const content = render(config, knowledge.rules, reviewers);

  if (opts.print) {
    process.stdout.write(content);
    return;
  }

  process.stderr.write(banner('review checklist') + '\n\n');

  const target = join(opts.root, opts.out ?? DEFAULT_OUT);
  if (existsSync(target) && !opts.force) {
    const existing = readFileSync(target, 'utf8');
    if (!existing.includes(MARKER)) {
      process.stderr.write(
        c.yellow(`  ${opts.out ?? DEFAULT_OUT} already exists and was not generated by Kavach.\n`) +
          c.grey('  Re-run with --force to replace it, or --out <path> to write elsewhere.\n\n'),
      );
      return;
    }
  }

  writeFileSync(target, content);
  process.stderr.write(
    `  ${c.green('✓')} wrote ${c.bold(relative(opts.root, target) || DEFAULT_OUT)}` +
      c.grey(` · ${reviewers.join(', ')}\n`),
  );

  const pointer = linkFromClaudeMd(opts.root, opts.out ?? DEFAULT_OUT);
  if (pointer) process.stderr.write(`  ${c.green('✓')} ${pointer}\n`);

  process.stderr.write(
    '\n' + c.grey('  Commit it so the team — and their coding agents — see it while writing.\n\n'),
  );
}

/**
 * Which reviewers apply to this project.
 *
 * Everything from the config's own routing preferences, plus what the detected
 * stack implies. A Go service should not be handed a React checklist.
 */
function relevantReviewers(config: KavachConfig): ReviewerName[] {
  // A checklist nobody finishes reading is worse than a short one. These three
  // apply to every codebase; the rest have to earn their place.
  const picked = new Set<ReviewerName>(['security', 'business-logic', 'architecture']);

  const stack = new Set(config.project.stack.map((s) => s.toLowerCase()));
  const language = config.project.language.toLowerCase();
  const framework = config.project.framework.toLowerCase();

  if (language === 'typescript' || stack.has('typescript')) picked.add('typescript');

  const isReact = stack.has('react') || ['next', 'remix', 'react'].includes(framework);
  const isWebUi = isReact || ['vue', 'nuxt', 'svelte', 'angular'].includes(framework);
  if (isReact) picked.add('react');
  if (isWebUi) picked.add('accessibility');

  if (config.project.testFramework !== 'unknown') picked.add('testing');

  // Performance is only worth a checklist where the common failure modes apply:
  // a UI that re-renders, or a backend with a data layer.
  const hasDataLayer =
    stack.has('prisma') ||
    stack.has('graphql') ||
    ['express', 'fastify', 'nest', 'django', 'go'].includes(framework);
  if (isWebUi || hasDataLayer) picked.add('performance');

  for (const forced of config.review.alwaysReviewers) {
    if ((REVIEWERS as string[]).includes(forced)) picked.add(forced as ReviewerName);
  }
  for (const excluded of config.review.neverReviewers) {
    picked.delete(excluded as ReviewerName);
  }

  return REVIEWERS.filter((r) => picked.has(r));
}

/** Pull the numbered Checklist section out of a reviewer rubric. */
function rubricChecklist(reviewer: ReviewerName): string[] {
  try {
    const text = readFileSync(join(PLUGIN_ROOT, 'skills', 'reviewers', `${reviewer}.md`), 'utf8');
    const section = /## Checklist\n([\s\S]*?)\n## /.exec(text);
    if (!section) return [];

    return section[1]
      .split(/\n(?=\d+\. )/)
      .map((item) =>
        item
          .replace(/^\d+\.\s*/, '')
          .split('\n')
          .map((l) => l.trim())
          .join(' ')
          .trim(),
      )
      .filter(Boolean);
  } catch {
    return [];
  }
}

const REVIEWER_TITLES: Record<ReviewerName, string> = {
  architecture: 'Structure and consistency',
  react: 'React',
  typescript: 'TypeScript',
  security: 'Security',
  performance: 'Performance',
  accessibility: 'Accessibility',
  testing: 'Tests',
  'business-logic': 'Behaviour and regressions',
};

function render(config: KavachConfig, rules: string, reviewers: ReviewerName[]): string {
  const { project } = config;
  const lines: string[] = [];

  lines.push(MARKER);
  lines.push('# Review checklist');
  lines.push('');
  lines.push(
    'What gets checked when a pull request is opened on this project. ' +
      '**Read it while writing the code, not after** — most review comments are ' +
      'avoidable by handling these up front.',
  );
  lines.push('');

  if (project.summary) {
    lines.push(`**This project:** ${project.summary}`);
    lines.push('');
  }

  const stack = [project.language, project.framework]
    .filter((v) => v && v !== 'unknown' && v !== 'none')
    .join(' · ');
  if (stack) {
    lines.push(`**Stack:** ${stack}${project.monorepo ? ' · monorepo' : ''}`);
    lines.push('');
  }

  // Project rules come first: they are the ones a generic checklist cannot know.
  const ownRules = extractRules(rules);
  if (ownRules.length > 0) {
    lines.push('## Rules for this project');
    lines.push('');
    lines.push('These are specific to this codebase and are checked on every PR.');
    lines.push('');
    for (const rule of ownRules) lines.push(`- [ ] ${rule}`);
    lines.push('');
  }

  if (project.focusAreas?.length) {
    lines.push('## Areas reviewed most closely');
    lines.push('');
    lines.push(
      `Changes touching ${project.focusAreas.map((a) => `**${a}**`).join(', ')} get the ` +
        'closest scrutiny. Expect questions if the reasoning is not obvious from the code.',
    );
    lines.push('');
  }

  lines.push('## What every PR is checked against');
  lines.push('');

  for (const reviewer of reviewers) {
    const items = rubricChecklist(reviewer);
    if (items.length === 0) continue;

    lines.push(`### ${REVIEWER_TITLES[reviewer]}`);
    lines.push('');
    for (const item of items) lines.push(`- [ ] ${item}`);
    lines.push('');
  }

  lines.push('## How findings are reported');
  lines.push('');
  lines.push(
    'Reviews are advisory and **never block a merge**. Anything uncertain arrives ' +
      'as a question rather than a defect claim, so answering it is enough.',
  );
  lines.push('');
  lines.push(`- Up to ${config.review.maxComments} inline comments per PR`);
  lines.push('- Critical and High findings are always shown, even past that cap');
  lines.push('- Repeat reviews of the same PR post nothing new');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    `<sub>Generated by [Kavach](https://github.com/O-Thinkitive-M/kavach) ${KAVACH_VERSION}. ` +
      'Regenerate with `/kavach-checklist` after changing project rules.</sub>',
  );
  lines.push('');

  return lines.join('\n');
}

/** Bullet lines from rules.md, minus the template boilerplate. */
function extractRules(rules: string): string[] {
  return rules
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith('- '))
    .map((l) => l.slice(2).trim())
    .filter((l) => l && !/^\(none yet\)$/i.test(l));
}

/**
 * Point CLAUDE.md at the checklist so a coding agent working in this repo
 * follows the same rules the reviewer will apply. Only touches an existing
 * file, and only once.
 */
function linkFromClaudeMd(root: string, outPath: string): string | null {
  const claudeMd = join(root, 'CLAUDE.md');
  if (!existsSync(claudeMd)) return null;

  try {
    const existing = readFileSync(claudeMd, 'utf8');
    if (existing.includes(outPath)) return null;

    writeFileSync(
      claudeMd,
      `${existing.trimEnd()}\n\n## Code review standards\n\n` +
        `Before finishing any change, check it against [\`${outPath}\`](${outPath}) — ` +
        'those are the criteria this project\'s PR review applies.\n',
    );
    return `added a pointer to CLAUDE.md`;
  } catch {
    return null;
  }
}
